version: "3.7"
services:
  backend:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/samrth?allowPublicKeyRetrieval=true    
    depends_on:
      mysqldb:
        condition: service_healthy
    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql
    environment:
      MYSQL_DATABASE: samrth
      MYSQL_ROOT_PASSWORD: 'Password'
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/logs:/logs
networks:
  springapimysql: